---
- name: install firewalld
  yum:
    name: firewalld
    state: latest

- name: start firewalld service
  service:
    name: firewalld
    state: started
    enabled: true

- name: configure firewalld
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    service: "{{firewall_service}}"
