---
- name: Install Apache and start the service
  hosts: webserver
  tasks:
    - name: "Install {{ ansible_local.custom.general.package}} package"
      yum:
        name: "{{ ansible_local.custom.general.package }}"
        state: latest

    - name: "Start the {{ansible_local.custom.general.service}} service"
      service:
        name: "{{ansible_local.custom.general.service}}"
        state: "{{ansible_local.custom.general.state}}"


