---

- name: Enable Intranet Access
  hosts: serverb.lab.example.com
  become: yes
  tasks:
    - name: latest version of httpd, firewalld, php, php-mysql and mariadb-server installed
      yum:
        name: 
          - firewalld
          - httpd
          - php
          - php-mysql
          - mariadb-server
        state: latest

    - name: firewalld enabled and started
      service:
        name: firewalld
        enabled: true
        state: started
   
    - name: firewalld allows connections to the ports used by httpd
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: httpd enabled and running
      service:
        name: httpd
        enabled: true
        state: started

    - name: mariadb enabled and running 
      service:
        name: mariadb
        enabled: true
        state: started

    - name: test php page installed
      get_url:
        url: "http://materials.example.com/grading/var/www/html/index.php"
        dest: "/var/www/html/index.php"
        mode: 0644





