---
- name: Setup facts on hosts
  hosts: lamp
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact

  tasks:
    - name: create directory
      file:
        state: directory
        recurse: yes
        path: "{{remote_dir}}"
    - name: copy facts file
      copy:
        src: "{{facts_file}}"
        dest: "{{remote_dir}}"

